/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e2e7ff',
        'secondary-container': '#d0e1fb',
        'on-primary-fixed': '#00174b',
        'primary-fixed': '#dbe1ff',
        'on-secondary-container': '#54647a',
        'surface-container': '#eaedff',
        outline: '#737686',
        'inverse-surface': '#283044',
        'on-primary-container': '#eeefff',
        'tertiary-container': '#bc4800',
        'surface-tint': '#0053db',
        'surface-bright': '#faf8ff',
        'inverse-primary': '#b4c5ff',
        'outline-variant': '#c3c6d7',
        'on-error': '#ffffff',
        tertiary: '#943700',
        'secondary-fixed-dim': '#b7c8e1',
        error: '#ba1a1a',
        secondary: '#505f76',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
        'tertiary-fixed-dim': '#ffb596',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary-container': '#ffede6',
        'on-primary-fixed-variant': '#003ea8',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-fixed-variant': '#38485d',
        'on-surface-variant': '#434655',
        primary: '#004ac6',
        'on-tertiary': '#ffffff',
        background: '#faf8ff',
        'tertiary-fixed': '#ffdbcd',
        'surface-container-low': '#f2f3ff',
        'on-surface': '#131b2e',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#360f00',
        'on-error-container': '#93000a',
        'surface-container-highest': '#dae2fd',
        surface: '#faf8ff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'primary-container': '#2563eb',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        md: '16px',
        gutter: '16px',
        'message-gap': '4px',
        xl: '32px',
        sm: '8px',
        xs: '4px',
        'thread-gap': '12px',
        base: '8px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
